version: '3.3'
            
services:
    parity:
        image: parity/parity:stable
        env_file: aurad_config.env
        volumes:
            - parity:/eth
        command: ["--light", "--jsonrpc-interface=all", "--base-path", "/eth"]
        ports:
            - "127.0.0.1:8545:8545"
            - "8546:8546"
            - "30303:30303"
            - "30303:30303/udp"
        healthcheck:
          test: ["CMD", "curl", "-f", "-H", "Content-Type: application/json", "--data", "{\"jsonrpc\":\"2.0\",\"method\":\"eth_blockNumber\",\"params\":[],\"id\":1}", "http://localhost:8545"]
          interval: 1m
          timeout: 10s
          retries: 3
        labels:
            - "autoheal"
        stop_signal: SIGINT
        stop_grace_period: 20s
        working_dir: /eth
        entrypoint: /bin/parity
        user: root
    mysql:
        image: mysql:5.7
        env_file: aurad_config.env
        volumes:
            - type: bind
              source: ${HOME}/.aurad/db
              target: /var/lib/mysql
        stop_signal: SIGINT
        stop_grace_period: 20s
        ports:
            - "127.0.0.1:33006:3306"
    aurad:
        image: auroradao/aurad:0.1.4
        depends_on:
          - "mysql"
        volumes:
          - type: bind
            source: ${HOME}/.aurad/downloads
            target: /usr/aurad/downloads
          - type: bind
            source: ${HOME}/.aurad/ipc
            target: /usr/aurad/ipc
        stop_signal: SIGINT
        stop_grace_period: 20s
        command: ["start", "pm2.config.js", "--no-daemon", "--only", "worker", "--kill-timeout", "5000"]
        healthcheck:
          test: ["CMD", "curl", "-f", "--insecure", "https://localhost:8443/health"]
          interval: 1m
          timeout: 10s
          retries: 3
        labels:
            - "autoheal"
        ports:
            - "8080:8080"
            - "8443:8443"
        env_file: aurad_config.env
        environment:
          - RPC_HOST
          - RPC_PROTOCOL
          - RPC_PORT
          - STAKING_HOST
        links:
          - "mysql:db.local"
volumes:
  parity:
